# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Expose the Flask application's default port
EXPOSE 4321

# Run the Flask application
CMD ["python", "flask_api.py", "--server.port=4321", "--server.address=0.0.0.0"]
